baseURL = 'https://danifreflow.github.io/danielfernandezcalvoCV.github.io/'
languageCode = 'en-us'
title = 'Daniel Fernández Calvo - sistemas infórmaticos y arquitectura'
theme = 'PaperMod'
relativeURLs = true
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "cv-tradicional"
    name = "CV Tradicional"
    url = "/cv-tradicional/"
    weight = 2

  [[menu.main]]
    identifier = "cv-infografico"
    name = "CV Infográfico"
    url = "/cv-infografico/"
    weight = 3

  [[menu.main]]
    identifier = "video-cv"
    name = "VideoCurrículum"
    url = "/video-cv/"
    weight = 4

  [[menu.main]]
    identifier = "posts"
    name = "Últimos Posts"
    url = "/posts/"
    weight = 5
